language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"  

notifications:
  email:
    recipients:
      - mirochaj@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
  
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - bash deploy.sh

after_success:
  - coveralls
	